### ISSUE TITLE
HD skin support

### ISSUE THREAD

**Issue by TheArmagan** [LKxth/minecraft-skins#1]
Your code should handle 128x skins too! Also must support multiples too.
Example 128x Skin: ![image](https://github.com/justcarlux/minecraft-skins/assets/30215038/f07c574f-6cb2-42c8-bd05-7abbebe92e92)

Example HD Skin: ![image](https://github.com/justcarlux/minecraft-skins/assets/30215038/ce4fa19f-1bc0-4fdd-bfe8-cb91bb8591a4)

**Comment by justcarlux** [comment]
hello! that's a great idea, i'm gonna be implementing this in the following days. thanks <3

**Comment by TheArmagan** [comment]
There is an example:
```js
const inputScale = Math.floor(image.width / 64);

// Draw Head
ctx.drawImage(image, 8 * inputScale, 8 * inputScale, 8 * inputScale, 8 * inputScale, 4 * outputScale, 0, 8 * outputScale, 8 * outputScale);
if (skinLayers) ctx.drawImage(image, 40 * inputScale, 8 * inputScale, 8 * inputScale, 8 * inputScale, 4 * outputScale, 0, 8 * outputScale, 8 * outputScale);
```

**Comment by justcarlux** [comment]
hello! @TheArmagan sorry for taking too long, i was kinda busy those days, but it's finally implemented :)
